version: "{build}"

clone_folder: c:\gopath\src\github.com\haccer\subjack

environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  
build: false

test_script:
  - go get github.com/haccer/available
  - go get github.com/miekg/dns
  - go get github.com/valyala/fasthttp
  - go build github.com/haccer/subjack
